config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  root to: 'visitors#index'
  post 'visitors/store'
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_info] = auth
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/visitors_controller.rb
require 'open-uri'
class VisitorsController < ApplicationController
  include Magick
  def index
    if session[:user_id]
      image = Magick::ImageList.new
      url_image = open(session[:user_info]['info']['image']) # Image Remote URL

      image.from_blob(url_image.read)
      url_image_width =  image.columns
      url_image_height = image.rows

      overlay_path = Rails.root.join("app/assets/images/check.png")
      overlay = Magick::Image.read(overlay_path).first
      test = overlay.resize_to_fit(url_image_width , url_image_height )
      image.composite!(test, Magick::CenterGravity, Magick::OverCompositeOp)
      image_name = session[:user_id]
      image.change_geometry!("800X800") { |cols, rows| image.thumbnail! cols, rows }
      image.write("public/image/#{image_name}.png")


      name = session[:user_info]['info']['name']
      # name = "sus"

      user_name = name.strip.split(/\s+/)[0]

      overlay_path = Rails.root.join("public/image/#{image_name}.png")
      overlay = Magick::Image.read(overlay_path).first
      title = Magick::Draw.new
      if user_name.length <= 7
        title.annotate(overlay, 0,0,0,-320, user_name) {
          self.font_family = 'Helvetica'
          self.fill = 'white'
          self.pointsize = 100
          self.gravity = CenterGravity
        }
      else
        title.annotate(overlay, 0,0,0,-320, user_name) {
        self.font_family = 'Helvetica'
        self.fill = 'white'
        self.pointsize = 100
        self.gravity = CenterGravity
      }
      end
      img = overlay.write("public/image/#{image_name}.png")
    end
  end

  def store
    @access_token = session[:user_info]['credentials']['token']
    @graph_api = Koala::Facebook::API.new(@access_token)
    begin
      sus = @graph_api.put_picture("#{Rails.root}/public/image/#{session[:user_id]}.png", '', {:message => "Vote for @Maggie Doyne Everyday @ www.heroes.cnn.com \n Visit http://fb-profile-overlay.herokuapp.com/ to show your support"}, "me")
    rescue => e
      return redirect_to root_url, :alert => "Sorry, something went wrong. Make sure You have accepted our every permission"
    end
    link_to_facebook = "https://www.facebook.com/photo.php?fbid=#{sus["id"]}&makeprofile=1"

    redirect_to link_to_facebook
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Maggie" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Maggie" %>">
    <meta property="og:title" content="Vote For Maggie Doyne" />
    <meta property="og:site_name" content="Fb Profile Overlay"/>
    <meta property="og:url" content="http://fb-profile-overlay.herokuapp.com/" />
    <meta property="og:description" content="App that changes the profile picture with the filter supporting Maggie Doyne win the title of CNN hero." />
<meta property="fb:app_id" content="555028044654300" />
<meta property="og:type" content="Web app" />
<meta property="article:author" content="https://www.facebook.com/sushant.bajracharya.3" />
<meta property="article:publisher" content="https://www.facebook.com/teamunx" />
<meta property="og:image"         content="http://fb-profile-overlay.herokuapp.com/default.jpg" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="container about">
        <div class="row">

          <%= yield %>
        </div>
      </div>
    </main>

  </body>
</html>

app/views/visitors/index.html.erb
<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 ">
  <div class="image text-center  main-image">
    <% if session[:user_info] %>
      <%= image_tag("/image/#{session[:user_id]}.png", class: "img-responsive") %><br>
      <%= form_tag({action: 'store'}) do %>
        <%= submit_tag("Upload To Facebook",class: "btn btn-info") %>
        <%= link_to 'Signout', signout_path, class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= image_tag('default.png', class:  "img-responsive") %><br>
      <%= link_to 'Login from Facebook', signin_path, class: "btn btn-primary" %>
    <% end %>

   </div>

   <!-- <div class="fb-like like-plugin" data-href="http://fuitter.com/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

   <a href="https://twitter.com/share" class="twitter-share-button like-plugin" data-url="http://www.fuitter.com" data-text="Vote for Maggie Doyne @ www.heroes.cnn.com Visit www.fuitter.com to show your support" data-via="sushantbaj">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
Tweet</a> -->
</div>
<div class="col-lg-5 col-md-12 col-sm-12 col-xs-12 ">
  <p class="text-center support">Supporters<br/><br/><b class="total"><%= User.count %></b> </p>
  <p class="text-center support">About Maggie<br/><br/>
    Maggie Doyne is an American philanthropist who has been recognized for her work helping to develop an orphanage and school in the Kopila Valley of Nepal after spending time in that country during a gap year after completing high school
   </p>
   <p>
    Visit <%= link_to("CNN Heroes", "http://heroes.cnn.com/") %> to vote for maggie <br>
    Supported by: <%= link_to("UNX", "http://livingunx.com/") %><br>
    Developed By: <%= link_to("Sushant Bajracharya", "https://plus.google.com/102164802283352741214/posts") %><br>
   </p>
   <p>
    <%= link_to("Privacy/Policy", 'needtochange') %>
   </p>
</div>